### ISSUE TITLE
Setup parse project

### ISSUE THREAD

**Issue by eveliotc** [eventinator/eventinator#3]

**Comment by miketehranian** [comment]
Our parse service is running on Heroku:
App name: lineupcodepath
App ID: lineupcodepath
Server URL: http://lineupcodepath.herokuapp.com/parse
Master Key: <PING ME FOR THE KEY>

You need to set the Master Key as an Environment Variable in your Xcode Simulator Schema. The Environment Variable Key is: "MASTER_KEY"
